# -*- coding: utf-8 -*-
# 30-Tage-Contentplan @gesundheitsakte — Phase 1 (nur Follow-CTA, kein Codewort)
# Format A folgt der Halbzeit-Regel: Aufloesung fruehestens auf halber Strecke.
# Format B folgt der Listen-Regel: Cover mit Versprechen, Beleg je Paar, Erkenntnis vor dem CTA.
# Format C folgt der Objekt-Regel: der Widerspruch steht im Objekt selbst, kein Overlay.
# Besetzung: 6 weibliche, 3 maennliche Faelle (19, 22, 29).

POSTS = [
dict(
 n=1,
 tag='Mo',
 w=1,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Der Espresso um 16 Uhr',
 hook='Sie schlief 8 Stunden und war trotzdem erschöpft. Der Grund lag 6 Stunden vorher.',
 slides=[
  'Cover — der Hook.',
  'Sie war beim Arzt. Blutbild in Ordnung, Schilddrüse in Ordnung, Eisen in Ordnung.',
  'Sie schläft ein wie ein Stein. Genau das war der Hinweis — nicht das Problem.',
  'Es lag nicht an der Dauer: 41, Bürojob, zwei Kinder, 22:30 ins Bett, 6:30 raus.',
  'Es lag an der ersten Nachthälfte. Dort passiert der meiste Tiefschlaf.',
  'Der Auslöser stand jeden Tag um 16 Uhr auf ihrem Schreibtisch.',
  'Koffein: nach 6 Stunden ist erst die Hälfte abgebaut. Nicht alles. Die Hälfte.',
  'Ihr Espresso um 16 Uhr wirkte um 22 Uhr noch — genau beim Zubettgehen.',
  'Einschlafen klappt trotzdem. Koffein blockiert die Müdigkeit, nicht die Erschöpfung.',
  'Sie zog den letzten Kaffee auf 13 Uhr vor. Sonst nichts.',
  'Payoff: Sie hat nicht mehr geschlafen. Sie hat zum ersten Mal seit Jahren wirklich geschlafen.',
  'CTA-Slide.',
 ],
 caption='Sie schlief acht Stunden und war trotzdem erschöpft.\n\nBeim Arzt war alles in Ordnung: Blutbild, Schilddrüse, Eisen. Sie schlief sogar besonders schnell ein — und genau das war der Hinweis.\n\nEs lag nicht an der Dauer. Es lag an der ersten Nachthälfte, in der der meiste Tiefschlaf passiert. Bei ihr fand er kaum statt.\n\nDer Auslöser stand jeden Tag um 16 Uhr auf ihrem Schreibtisch. Koffein hat eine Halbwertszeit von etwa 5 bis 6 Stunden — nach sechs Stunden ist erst die Hälfte abgebaut. Ihr Espresso um 16 Uhr wirkte um 22 Uhr noch, genau beim Zubettgehen.\n\nEinschlafen klappt trotzdem, denn Koffein blockiert den Müdigkeitsdruck, nicht die Erschöpfung darunter.\n\nSie hat eine Sache geändert: letzter Kaffee um 13 Uhr statt 16 Uhr.\n\nSie hat danach nicht mehr geschlafen. Sie hat zum ersten Mal seit Jahren wirklich geschlafen.\n\nWann trinkst du deinen letzten Kaffee? 👇',
 bild='a cold espresso cup on an office desk beside a keyboard, late afternoon light through blinds',
 ziel='Kommentar (Uhrzeit nennen)'),

dict(
 n=2,
 tag='Di',
 w=1,
 fmt='B',
 art='Karussell · 8 Slides',
 titel='Iss Protein, nicht Proteinriegel',
 hook='Iss Protein / nicht Proteinriegel',
 slides=[
  'Iss Protein / nicht Proteinriegel',
  'Iss Obst / nicht Smoothie',
  'Trink Wasser / nicht Vitaminwasser',
  'Iss Haferflocken / nicht Frühstückscerealien',
  'Iss Kartoffeln / nicht Kartoffelchips',
  'Iss Joghurt natur / nicht Fruchtjoghurt',
  'Geh spazieren / nicht in die Sauna',
  'CTA-Slide.',
 ],
 caption='Sieben Sätze, die im Supermarkt mehr entscheiden als jede Diät.\n\nEs geht nicht um Verbote. Es geht darum, dass die zweite Variante fast immer teurer ist, schneller verdaut wird und weniger satt macht als die erste — bei ähnlichem Preis pro Kalorie.\n\nEin Fruchtjoghurt hat oft so viel Zucker wie eine Handvoll Gummibärchen. Ein Smoothie liefert die Kalorien von drei Äpfeln, aber nicht deren Ballaststoffe. Ein Proteinriegel ist Süßigkeit mit Eiweiß drin.\n\nDu musst nichts davon streichen. Du musst nur wissen, was du gerade isst.\n\nWelchen Punkt hättest du nicht erwartet? 👇',
 bild='two paper grocery bags on a kitchen counter, morning light, vegetables visible at the top',
 ziel='Speichern'),

dict(
 n=3,
 tag='Mi',
 w=1,
 fmt='R',
 art='Reel · 22 Sek.',
 titel='10 Minuten nach dem Essen',
 hook='10 Minuten gehen nach dem Essen. Nicht wegen der Kalorien.',
 slides=[
  '0–3 Sek: 10 Minuten gehen nach dem Essen — Nicht wegen der Kalorien.',
  '3–9 Sek: Nach jeder Mahlzeit steigt dein Blutzucker — Der Anstieg ist normal. Interessant ist, wie hoch die Spitze wird.',
  '9–15 Sek: Arbeitende Muskeln ziehen Glukose aus dem Blut — Auch ohne Insulin. Allein dadurch, dass sie sich bewegen.',
  '15–19 Sek: Deshalb fällt die Spitze flacher aus — Wenn du gehst statt sitzt. Einmal um den Block reicht.',
  '19–22 Sek: Endcard mit Signet und Handle.',
 ],
 caption='10 Minuten gehen nach dem Essen. Nicht wegen der Kalorien.\n\nZwei Stockwerke Treppe oder einmal um den Block verbrennen fast nichts. Darum geht es hier auch nicht.\n\nNach jeder Mahlzeit steigt dein Blutzucker — das ist normal und soll so sein. Interessant ist, wie hoch die Spitze ausfällt und wie lange sie oben bleibt.\n\nArbeitende Muskeln nehmen Glukose auch unabhängig von Insulin aus dem Blut auf. Sie holen sich den Zucker einfach, weil sie ihn gerade brauchen. Deshalb fällt die Spitze flacher aus, wenn du nach dem Essen gehst statt sitzt — das ist in Untersuchungen messbar, schon nach wenigen Minuten.\n\nKein Sport, kein Schwitzen, keine Ausrüstung. Einmal um den Block.\n\nDer beste Zeitpunkt ist direkt nach dem Essen, nicht zwei Stunden später.\n\nSpeicher dir das für nach dem Mittagessen. 👇',
 bild='Reel-B-Roll: Schuhe im Flur, Beine auf Gehweg von hinten, Küchentür fällt zu',
 ziel='Speichern'),

dict(
 n=4,
 tag='Do',
 w=1,
 fmt='C',
 art='Einzelbild',
 titel='Der Kassenbon',
 hook='Meal Prep Sonntag 11,40 € — Lieferdienst Dienstag 27,90 €',
 slides=[
  'Ein Bild: Kassenbon, auf dem beide Zeilen untereinander gedruckt stehen. Text ist Teil des Objekts, kein Overlay.',
 ],
 caption='Zwei Zeilen auf einem Kassenbon.\n\nDer Vergleich ist unfair, ich weiß. Der Sonntag kostet dich anderthalb Stunden, der Dienstag kostet dich zwölf Minuten Warten.\n\nAber genau das ist der Punkt: Es ist keine Frage von Disziplin, sondern eine Frage von Zeitpunkt. Am Sonntag hast du die Zeit. Am Dienstag um 19:40 Uhr hast du sie nicht — und triffst trotzdem die Entscheidung für den ganzen Abend.\n\nDie Entscheidung fällt nicht abends. Sie fällt am Sonntag.\n\nKochst du vor? 👇',
 bild='close-up photograph of a printed supermarket receipt held in one hand, dark wooden table, cool side light',
 ziel='Kommentar (ja/nein)'),

dict(
 n=5,
 tag='Fr',
 w=1,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Der Stuhl mit 22',
 hook='Ihr Rücken riss mit 45. Angefangen hat es mit einem Stuhl mit 22.',
 slides=[
  'Cover — der Hook.',
  'Zwei Physiotherapien, drei Röntgenbilder. Auf keinem Bild war etwas Auffälliges zu sehen.',
  'Das Ziehen kam nie beim Heben. Es kam beim Aufstehen. Auch das war ein Hinweis.',
  'Es lag nicht an einer Verletzung: erste Bürostelle mit 22, acht Stunden sitzen, neun mit Pendeln.',
  'Es lag nicht am Rücken selbst. Der Rücken war der Ort, nicht die Ursache.',
  'Die Ursache saß vorne — in der Hüfte.',
  'Bei dauerndem Sitzen verkürzt die Hüftbeugemuskulatur. Das Becken kippt nach vorn.',
  'Der untere Rücken arbeitet dann dagegen. Dauerhaft, ohne Pause, jahrelang.',
  'Deshalb half Dehnen nur kurz: es änderte die Spannung, nicht die Sitzzeit.',
  'Was half: alle 30 Minuten aufstehen. Zwei Minuten reichen.',
  'Payoff: Der beste Zeitpunkt dafür war mit 22. Der zweitbeste ist der nächste Kaffee.',
  'CTA-Slide.',
 ],
 caption='Ihr Rücken riss mit 45. Angefangen hat es mit einem Stuhl mit 22.\n\nZwei Physiotherapien, drei Röntgenbilder — auf keinem Bild war etwas Auffälliges. Das Ziehen kam nie beim Heben, sondern beim Aufstehen.\n\nEs lag nicht an einer Verletzung. Erste Bürostelle mit 22, acht Stunden sitzen, neun mit Pendeln. Und es lag auch nicht am Rücken selbst — der war nur der Ort, an dem es wehtat.\n\nDie Ursache saß vorne. Bei dauerndem Sitzen verkürzt die Hüftbeugemuskulatur, das Becken kippt nach vorn, und der untere Rücken arbeitet dagegen. Dauerhaft, ohne Pause, über Jahre.\n\nDeshalb half Dehnen immer nur kurz: Es änderte die Spannung, nicht die Sitzzeit.\n\nWas geholfen hat: alle 30 Minuten aufstehen. Zwei Minuten reichen.\n\nDer beste Zeitpunkt dafür war mit 22. Der zweitbeste ist der nächste Kaffee.\n\nWie lange sitzt du am Stück? 👇',
 bild='an empty office chair in a dim room, late evening, one desk lamp, long shadow on the floor',
 ziel='Kommentar (Stunden nennen)'),

dict(
 n=6,
 tag='Sa',
 w=1,
 fmt='R',
 art='Reel · 25 Sek.',
 titel='30 Gramm vor 10 Uhr',
 hook='30 Gramm Eiweiß vor 10 Uhr. Ohne Shake. Ohne Kochen.',
 slides=[
  '0–3 Sek: 30 Gramm Eiweiß vor 10 Uhr — Ohne Shake. Ohne Kochen.',
  '3–9 Sek: 250 Gramm Skyr sind 25 Gramm Eiweiß — Eine Schüssel, ein Löffel. Kein Rezept, keine Waage.',
  '9–15 Sek: Beeren dazu, ein Löffel Nüsse — Damit bist du über 30 Gramm und hast zwei Minuten gebraucht.',
  '15–21 Sek: Warum ausgerechnet morgens? — Eiweiß sättigt länger als die gleiche Menge Kohlenhydrate. Wer früh satt ist, entscheidet mittags ruhiger.',
  '21–25 Sek: Endcard mit Signet und Handle.',
 ],
 caption='30 Gramm Eiweiß vor 10 Uhr. Ohne Shake, ohne Kochen.\n\n250 Gramm Skyr liefern rund 25 Gramm. Eine Handvoll Beeren und ein Löffel Nüsse dazu — und du bist drüber. Zwei Minuten, kein Mixer, kein Rezept.\n\nWarum ausgerechnet morgens: Eiweiß sättigt pro Kalorie stärker als Kohlenhydrate oder Fett. Wer früh satt ist, trifft die Entscheidung um halb eins ruhiger — und das ist meistens die Mahlzeit, an der ein Tag kippt.\n\nEs muss kein Skyr sein. Magerquark, Hüttenkäse, zwei bis drei Eier oder griechischer Joghurt kommen auf ähnliche Werte. Nimm das, was ohnehin bei dir im Kühlschrank steht.\n\nUnd nein, du musst das nicht abwiegen. Ein Becher ist ein Becher.\n\nSpeicher dir das für morgen früh. 👇',
 bild='Reel-B-Roll: Hände-POV von oben, Schüssel, Löffel, Beeren, helle Küchenarbeitsplatte',
 ziel='Speichern'),

dict(
 n=7,
 tag='So',
 w=1,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Mal gewinnt die langweilige Variante',
 hook='Sechs davon kennst du. Beim siebten scheitern die meisten.',
 slides=[
  'Cover: Sieben Mal gewinnt die langweilige Variante — Sechs davon kennst du. Beim siebten scheitern die meisten.',
  'Schlaf 7 Stunden / nicht 5 plus Mittagsschlaf — Beleg: Der Tiefschlaf sitzt in der ersten Nachthälfte. Ein Nickerchen holt ihn nicht nach.',
  'Geh 8.000 Schritte / nicht dreimal die Woche Cardio — Beleg: Jeden Tag 300 Kalorien schlagen dreimal 300 Kalorien pro Woche.',
  'Iss dreimal / nicht sechsmal — Beleg: Sechs Mahlzeiten verbrennen nicht mehr. Sie sind nur sechs Entscheidungen.',
  'Heb schwer / nicht oft — Beleg: Der Reiz kommt von der Last. Nicht von der Zahl der Wiederholungen.',
  'Miss einmal die Woche / nicht täglich — Beleg: Dein Gewicht schwankt am Tag um bis zu zwei Kilo. Das ist Wasser, nicht Fett.',
  'Fang mit zwei Trainings an / nicht mit fünf — Beleg: Zwei Einheiten machst du im November noch. Fünf nicht.',
  'Halte 12 Monate durch / nicht 6 Wochen perfekt — Beleg: Nach sechs perfekten Wochen bist du im Februar raus. Das ist der Punkt, an dem die meisten aufgeben.',
  'Erkenntnis: Die rechte Spalte ist nicht falsch. Sie ist nur nicht durchhaltbar.',
  'CTA-Slide.',
 ],
 caption='Sieben Mal gewinnt die langweilige Variante.\n\nDer Grund ist immer derselbe: Die linke Spalte hältst du zwölf Monate durch, die rechte sechs Wochen. Und zwölf mittelmäßige Monate schlagen sechs perfekte Wochen — jedes Mal.\n\nZwei davon werden am häufigsten falsch gemacht.\n\nDas tägliche Wiegen: Dein Gewicht schwankt innerhalb eines Tages um bis zu zwei Kilo, allein durch Wasser, Salz und Darminhalt. Wer jeden Morgen draufsteht, misst Rauschen und hält es für Fortschritt oder Rückschritt.\n\nUnd der Start mit fünf Einheiten: Fast jeder, der im Januar mit fünf anfängt, macht im März null. Wer mit zwei anfängt, macht im März immer noch zwei.\n\nDie rechte Spalte ist nicht falsch. Sie ist nur nicht durchhaltbar.\n\nWelcher Punkt trifft dich gerade? 👇',
 bild='Leere Laufbahn im Morgengrauen, verblasste Bahnmarkierungen, keine Menschen',
 ziel='Kommentar'),

dict(
 n=8,
 tag='Mo',
 w=2,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Der Fehler in Woche 3',
 hook='Sie nahm 12 Kilo ab. Und 14 wieder zu. Der Fehler passierte in Woche 3.',
 slides=[
  'Cover — der Hook.',
  'Sie hat nicht geschummelt. Sie hat alles gewogen, jeden Tag, elf Wochen lang.',
  'Woche 1: minus 2,4 kg. Woche 2: minus 1,1. Woche 3: nichts.',
  'Es lag nicht an der Disziplin: 1.200 kcal am Tag, fünfmal Sport die Woche.',
  'Es lag auch nicht am Wasser. Nach drei weiteren Wochen stand die Zahl immer noch.',
  'Der Körper hatte reagiert — auf genau das, was sie für richtig hielt.',
  'Bei starkem Defizit sinkt der Energieverbrauch, gleichzeitig steigt der Hunger. Messbar.',
  'Bei wenig Eiweiß und viel Cardio geht zusätzlich Muskelmasse verloren.',
  'Weniger Muskeln heißt weniger Grundumsatz. Der Boden sinkt mit — deshalb half weniger essen nicht.',
  'Zweiter Versuch: kleineres Defizit, deutlich mehr Eiweiß, zweimal Krafttraining.',
  'Payoff: Sie brauchte elf Monate statt vier. Das war der Punkt, an dem es zum ersten Mal blieb.',
  'CTA-Slide.',
 ],
 caption='Sie nahm 12 Kilo ab. Und 14 wieder zu. Der Fehler passierte in Woche 3.\n\nSie hat nicht geschummelt — alles gewogen, jeden Tag. Woche 1: minus 2,4 kg. Woche 2: minus 1,1. Woche 3: nichts. Und auch nach drei weiteren Wochen stand die Zahl.\n\nEs lag nicht an der Disziplin. 1.200 Kalorien am Tag, fünfmal Sport. Der Körper hatte reagiert — auf genau das, was sie für richtig hielt.\n\nBei starkem Defizit sinkt der Energieverbrauch, während der Hunger steigt. Kommt wenig Eiweiß und viel Cardio dazu, geht zusätzlich Muskelmasse verloren. Weniger Muskeln heißt weniger Grundumsatz. Der Boden sinkt also mit — deshalb half noch weniger essen nicht.\n\nBeim zweiten Versuch: kleineres Defizit, deutlich mehr Eiweiß, zweimal Krafttraining. Sie brauchte elf Monate statt vier.\n\nDas war der Punkt, an dem es zum ersten Mal blieb.\n\nWie viele Anläufe hattest du schon? 👇',
 bild='an old kitchen scale on a windowsill, grey winter light, faded numbers',
 ziel='Kommentar (Anzahl)'),

dict(
 n=9,
 tag='Di',
 w=2,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Sätze, die dich nichts kosten',
 hook='Keiner dieser sieben Punkte kostet einen Cent. Der letzte spart dir sogar welche.',
 slides=[
  'Cover: Sieben Änderungen, die nichts kosten — Keine Nahrungsergänzung, kein Abo, kein Gerät. Der letzte spart dir sogar Geld.',
  'Iss am Tisch / nicht am Bildschirm — Beleg: Wer nebenbei isst, isst im Schnitt mehr — und merkt es nicht.',
  'Stell das Obst nach vorn / nicht in die Schublade — Beleg: Du isst, was du siehst. Das ist kein Charakter, das ist Sichtweite.',
  'Iss zuerst das Eiweiß / nicht zuerst das Brot — Beleg: Gleiche Mahlzeit, andere Reihenfolge: Du bist früher satt und der Blutzucker steigt flacher.',
  'Koch die doppelte Menge / nicht zweimal neu — Beleg: Dieselbe Zeit am Herd, zwei Abende versorgt. Der zweite Abend ist der, an dem du sonst bestellst.',
  'Trink ein Glas Wasser vorweg / nicht während des Essens hinterher — Beleg: Morgens ist der Körper am trockensten. Was sich wie Hunger anfühlt, ist oft Durst.',
  'Kauf klein ein / nicht auf Vorrat — Beleg: Was im Schrank steht, wird gegessen. Vorrat ist kein Sparen, wenn es früher leer ist.',
  'Schreib die Woche auf / nicht jeden Tag neu entscheiden — Beleg: Zwölf Minuten Planung am Sonntag ersetzen sieben Entscheidungen um 19:40 Uhr.',
  'Erkenntnis: Keiner dieser Punkte verbietet dir etwas. Sie ändern nur, wie leicht die richtige Entscheidung fällt.',
  'CTA-Slide.',
 ],
 caption='Sieben Änderungen, die dich nichts kosten.\n\nKeine Nahrungsergänzung, kein Abo, kein Gerät. Und trotzdem entscheidet die Liste mehr als jede Diät — weil sie nicht deinen Willen anspricht, sondern deine Umgebung.\n\nDas ist der Punkt, den die meisten übersehen: Du isst, was du siehst. Du isst, was da ist. Du isst mehr, wenn du nebenbei isst. Nichts davon ist Charakterschwäche, das ist einfach so.\n\nDie Reihenfolge auf dem Teller ist der Punkt, den fast niemand kennt. Dieselbe Mahlzeit, erst das Eiweiß und das Gemüse, dann die Kohlenhydrate — du bist früher satt und der Blutzucker steigt flacher an. Es kostet dich nichts außer der Gewohnheit.\n\nKeiner dieser Punkte verbietet dir etwas. Sie ändern nur, wie leicht die richtige Entscheidung fällt.\n\nWelchen probierst du diese Woche? 👇',
 bild='Küchentisch von oben, eine Obstschale im Vordergrund scharf, dahinter unscharf ein Laptop',
 ziel='Kommentar'),

dict(
 n=10,
 tag='Mi',
 w=2,
 fmt='R',
 art='Reel · 20 Sek.',
 titel='Zwei Frühstücke',
 hook='Zwei Frühstücke. Gleiche Kalorien. Vier Stunden Unterschied.',
 slides=[
  '0–3 Sek: Zwei Frühstücke. Gleiche Kalorien. — Vier Stunden Unterschied.',
  '3–8 Sek: Links Cerealien. Rechts Rührei mit Brot. — Beide rund 400 Kalorien.',
  '8–13 Sek: Links 8 Gramm Eiweiß. Rechts 24. — Dreimal so viel bei derselben Kalorienzahl.',
  '13–18 Sek: Der Unterschied zeigt sich nicht morgens — sondern um elf.',
  '18–21 Sek: Endcard mit Signet und Handle.',
 ],
 caption='Zwei Frühstücke. Gleiche Kalorien. Vier Stunden Unterschied.\n\nLinks: Cerealien mit Milch. Rechts: Rührei mit einer Scheibe Brot. Beide liegen bei rund 400 Kalorien — auf dem Papier identisch.\n\nDer Unterschied steht woanders: links etwa 8 Gramm Eiweiß, rechts etwa 24. Dreimal so viel, bei derselben Kalorienzahl.\n\nGemerkt wird das nicht beim Frühstück. Gemerkt wird es um elf, wenn der eine Magen ruhig ist und der andere nach etwas Süßem verlangt. Eiweiß sättigt pro Kalorie am stärksten — und wer um elf satt ist, entscheidet mittags anders.\n\nEs geht nicht darum, Cerealien zu verbieten. Es geht darum zu wissen, warum du zwei Stunden später wieder in der Küche stehst.\n\nWas isst du morgens? 👇\n\n—\nBild- und Videomaterial KI-generiert.',
 bild='Reel-B-Roll: Split-Screen zweier Frühstücksteller von oben, gleiche Tischplatte, gleiches Licht',
 ziel='Speichern'),

dict(
 n=11,
 tag='Do',
 w=2,
 fmt='C',
 art='Einzelbild',
 titel='Der Fitness-Vertrag',
 hook='Mitgliedsvertrag, Kündigungsdatum eingetragen: 14. Februar. Ausgestellt am 2. Januar.',
 slides=[
  'Ein Bild: ausgefüllter Fitnessstudio-Vertrag auf einem Tresen. Beitrittsdatum 02.01., im Feld darunter ein bereits eingetragenes Kündigungsdatum 14.02. Beides gedruckt bzw. handschriftlich im Formular — kein Overlay, kein Zettel daneben.',
 ],
 caption='Beitritt am 2. Januar. Kündigung am 14. Februar.\n\nSechs Wochen. Das ist die Strecke, die der Januar-Vorsatz im Schnitt trägt — und der Grund ist fast nie, dass jemand faul war.\n\nDer Fehler passiert am Tag der Anmeldung: fünf Einheiten pro Woche, alles gleichzeitig, ab Montag. Das funktioniert drei Wochen, weil Neues trägt. In Woche vier kommt eine Grippe, ein Projekt, ein Kind mit Fieber. Und weil der Plan keinen schlechten Tag vorgesehen hat, gibt es danach keinen Weg zurück hinein.\n\nWer mit zwei Einheiten anfängt, macht im März immer noch zwei.\n\nEs geht nicht darum, weniger zu wollen. Es geht darum, den Plan so zu bauen, dass er einen schlechten Februar überlebt.\n\nWann hast du zuletzt gekündigt? 👇',
 bild='Ausgefüllter Vertrag auf einem Tresen, Kugelschreiber daneben, kühles Seitenlicht',
 ziel='Kommentar (Häufigkeit)'),

dict(
 n=12,
 tag='Fr',
 w=2,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Immer müde',
 hook='Drei Ärzte sagten ihr, die Werte seien in Ordnung. Der vierte schaute auf einen einzigen davon genauer.',
 slides=[
  'Cover — der Hook.',
  'Sie schlief acht Stunden, machte Sport, aß vernünftig. Trotzdem: seit einem Jahr erschöpft.',
  'Beim Treppensteigen ging ihr die Luft aus. Mit 34.',
  'Es lag nicht an einer Krankheit: Blutbild unauffällig, Hämoglobin im Normbereich.',
  'Und genau dieser Normbereich war das Problem.',
  'Hämoglobin zeigt den Transport. Nicht den Vorrat.',
  'Der Vorratswert heißt Ferritin — und steht in keinem Standard-Blutbild.',
  'Bei starker Menstruation ist der monatliche Verlust höher. Über Jahre summiert sich das.',
  'Typische Zeichen: Erschöpfung, Kurzatmigkeit bei Belastung, Haarausfall.',
  'Sie ließ Ferritin bestimmen. Der Wert war niedrig.',
  'Payoff: Es war nie ihre Disziplin. Es war ein Wert, nach dem niemand gefragt hatte.',
  'CTA-Slide.',
 ],
 caption='Drei Ärzte sagten ihr, die Werte seien in Ordnung.\n\n34 Jahre. Sie schlief acht Stunden, machte Sport, aß vernünftig — und war seit einem Jahr erschöpft. Beim Treppensteigen ging ihr die Luft aus.\n\nEs lag nicht an einer Krankheit. Das Blutbild war unauffällig, Hämoglobin im Normbereich. Und genau dieser Normbereich war das Problem.\n\nHämoglobin zeigt den Transport, nicht den Vorrat. Der Vorratswert heißt Ferritin und steht in keinem Standard-Blutbild. Bei starker Menstruation ist der monatliche Verlust höher — über Jahre summiert sich das.\n\nTypische Zeichen: anhaltende Erschöpfung, Kurzatmigkeit bei Belastung, Haarausfall.\n\nSie ließ Ferritin bestimmen. Der Wert war niedrig. Nach drei Monaten Behandlung war die Erschöpfung weg.\n\nEs war nie ihre Disziplin. Es war ein Wert, nach dem niemand gefragt hatte.\n\nWichtig, und das ist kein Nebensatz: Eisen niemals auf Verdacht einnehmen. Zu viel Eisen ist ein eigenes gesundheitliches Problem. Das gehört in ärztliche Hände.\n\nDieser Beitrag informiert und ersetzt keine ärztliche Beratung.',
 bild='a laboratory tube rack on a white surface, single cool light, shallow depth of field, no faces',
 ziel='Speichern'),

dict(
 n=13,
 tag='Sa',
 w=2,
 fmt='R',
 art='Reel · 18 Sek.',
 titel='3:14 Uhr',
 hook='Du wachst nachts immer zur selben Zeit auf? Das ist kein Zufall.',
 slides=[
  '0–4 Sek: Makro, Wecker zeigt 3:14, dunkler Raum.',
  '4–10 Sek: Nach etwa vier Stunden endet der Tiefschlafanteil, der Schlaf wird leichter.',
  '10–15 Sek: In dieser Phase weckt dich, was du vorher nicht bemerkt hättest: Alkohol, Wärme, Stress.',
  '15–18 Sek: Endcard.',
 ],
 caption='Immer um dieselbe Zeit wach?\n\nDer Anteil an Tiefschlaf ist in der ersten Nachthälfte am größten. Danach wird der Schlaf von Zyklus zu Zyklus leichter — und in einer leichten Phase weckt dich, was dich vorher nicht gestört hätte.\n\nAlkohol am Abend, ein zu warmes Zimmer, ein unfertiger Gedanke. Der Auslöser ist selten neu. Nur deine Schlaftiefe ist eine andere.\n\nKennst du deine Uhrzeit? 👇',
 bild='Reel-B-Roll: Makro eines Weckers bei 3:14, dunkles Schlafzimmer, ein schmaler Lichtstreifen',
 ziel='Kommentar (Uhrzeit)'),

dict(
 n=14,
 tag='So',
 w=2,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Sätze über Krafttraining',
 hook='Sieben Sätze über Krafttraining. Der fünfte kostet die meisten ein Jahr.',
 slides=[
  'Cover: Sieben Sätze über Krafttraining — Sechs sind schnell erklärt. Der fünfte kostet die meisten ein ganzes Jahr.',
  'Lern fünf Übungen / nicht fünfzig — Beleg: Kniebeuge, Kreuzheben, Drücken, Ziehen, Tragen. Der Rest sind Varianten davon.',
  'Trainier den ganzen Körper / nicht einen Muskel pro Tag — Beleg: Zweimal die Woche ganzer Körper schlägt fünfmal die Woche Einzelteile — wenn du nur zweimal kommst.',
  'Steigere das Gewicht / nicht die Dauer — Beleg: Der Muskel reagiert auf mehr Last. Nicht auf mehr Zeit unter derselben.',
  'Mach zwei Sätze richtig / nicht fünf halbe — Beleg: Der letzte saubere Satz zählt. Die drei danach in schlechter Form zählen negativ.',
  'Ruh 48 Stunden / nicht täglich denselben Muskel — Beleg: Der Muskel wächst in der Pause, nicht im Training. Ohne Pause trainierst du gegen dich.',
  'Führ ein Trainingsbuch / nicht verlass dich auf dein Gefühl — Beleg: Wer nicht aufschreibt, hebt in Woche 10 dasselbe wie in Woche 2. Und wundert sich.',
  'Trainier für mit 70 / nicht für den Sommer — Beleg: Ab 30 verlierst du ohne Training 3 bis 8 Prozent Muskelmasse pro Jahrzehnt. Das Training hält, was du sonst abgibst.',
  'Erkenntnis: Krafttraining ist keine Optik-Entscheidung. Es ist die einzige Maßnahme, die dir mit 70 das Aufstehen erhält.',
  'CTA-Slide.',
 ],
 caption='Sieben Sätze über Krafttraining.\n\nDer fünfte kostet die meisten ein ganzes Jahr: Der Muskel wächst in der Pause, nicht im Training. Wer jeden Tag denselben Muskel reizt, trainiert gegen sich selbst und nennt es Fleiß.\n\nDer wichtigste steht am Ende. Ab etwa 30 verliert man ohne Training rund 3 bis 8 Prozent Muskelmasse pro Jahrzehnt, und der Verlust beschleunigt sich später. Man merkt es nicht mit 40. Man merkt es an dem Tag, an dem man sich beim Aufstehen abstützt.\n\nKrafttraining ist deshalb keine Optik-Entscheidung. Es ist die einzige Maßnahme, die dir mit 70 das Treppensteigen erhält.\n\nFünf Übungen reichen. Kniebeuge, Kreuzheben, Drücken, Ziehen, Tragen.\n\nWomit fängst du an? 👇',
 bild='Langhantel auf dunklem Studioboden, seitliches Licht, niemand im Bild',
 ziel='Kommentar'),

dict(
 n=15,
 tag='Mo',
 w=3,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Ab 30 verlierst du',
 hook='Mit 62 stand sie vom Stuhl auf und musste sich abstützen. Verloren hatte sie es mit 34.',
 slides=[
  'Cover — der Hook.',
  'Sie war nie krank. Kein Herz, keine Gelenke, keine Diagnose in 62 Jahren.',
  'Und sie hat es nicht kommen sehen. Es gab keinen Tag, an dem es auffiel.',
  'Es lag nicht am Alter allein: Ihre Nachbarin, 71, stand ohne Hände auf.',
  'Der Unterschied lag 28 Jahre zurück — bei einem Umzug ins Erdgeschoss.',
  'Ab etwa 30 verliert der Körper ohne Reiz Muskelmasse.',
  'Schätzungen liegen bei rund 3 bis 8 Prozent pro Jahrzehnt. Bei Inaktivität mehr.',
  'Das merkt niemand. Bis eine Bewegung nicht mehr geht, die dreißig Jahre lang ging.',
  'Der Muskel selbst bleibt bis ins hohe Alter trainierbar — das ist der entscheidende Teil.',
  'Sie fing mit 62 an. Zweimal die Woche, mit Anleitung.',
  'Payoff: Nach acht Monaten stand sie ohne Hände auf. Das klingt nach wenig. Für sie war es alles.',
  'CTA-Slide.',
 ],
 caption='Mit 62 stand sie vom Stuhl auf und musste sich abstützen. Verloren hatte sie es mit 34.\n\nSie war nie krank — kein Herz, keine Gelenke, keine Diagnose in 62 Jahren. Und sie hat es nicht kommen sehen: Es gab keinen Tag, an dem es auffiel.\n\nEs lag nicht am Alter allein. Ihre Nachbarin, 71, stand ohne Hände auf. Der Unterschied lag 28 Jahre zurück, bei einem Umzug ins Erdgeschoss.\n\nAb etwa 30 verliert der Körper ohne Trainingsreiz Muskelmasse — Schätzungen liegen bei rund 3 bis 8 Prozent pro Jahrzehnt, bei Inaktivität mehr. Man merkt es nicht, bis eine Bewegung nicht mehr geht, die dreißig Jahre lang ging.\n\nDer entscheidende Teil steckt im selben Befund: Muskeln bleiben bis ins hohe Alter trainierbar. Es gibt kein Alter, in dem sich das nicht mehr lohnt.\n\nSie fing mit 62 an, zweimal die Woche, mit Anleitung. Nach acht Monaten stand sie ohne Hände auf.\n\nDas klingt nach wenig. Für sie war es alles.',
 bild='an empty wooden chair by a window in an old apartment, afternoon light, worn floorboards',
 ziel='Teilen'),

dict(
 n=16,
 tag='Di',
 w=3,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Sätze über Sattwerden',
 hook='Sieben Sätze über Sattwerden. Beim dritten liegen fast alle falsch.',
 slides=[
  'Cover: Sieben Sätze über Sattwerden — Es geht nicht um Willenskraft. Beim dritten liegen fast alle falsch.',
  'Iss langsam / nicht wenig — Beleg: Das Sättigungssignal braucht rund 20 Minuten. Wer in 10 isst, isst 10 Minuten zu viel.',
  'Hör auf bei satt / nicht bei leer — Beleg: Der Teller ist kein Maß. Er wurde befüllt, bevor du Hunger hattest.',
  'Nimm den kleinen Teller / nicht die halbe Portion — Beleg: Dieselbe Menge sieht auf einem kleinen Teller nach mehr aus. Dein Auge isst mit, ob du willst oder nicht.',
  'Iss vor dem Einkaufen / nicht danach — Beleg: Hungrig eingekauft landet mehr im Wagen — und anderes. Das ist messbar, nicht anekdotisch.',
  'Plan den Nachtisch ein / nicht weg — Beleg: Was verboten ist, wird interessant. Was eingeplant ist, wird eine Portion.',
  'Iss mehr Eiweiß / nicht weniger von allem — Beleg: Eiweiß sättigt pro Kalorie am stärksten. Du isst nicht weniger — du isst anderes.',
  'Erlaub dir alles / nicht ständig alles — Beleg: Ein Lebensmittel macht dich nicht dick. Die Häufigkeit tut es.',
  'Erkenntnis: Sattwerden ist kein Willensakt. Es ist eine Frage von Zeit, Reihenfolge und Tellergröße.',
  'CTA-Slide.',
 ],
 caption='Sieben Sätze über Sattwerden.\n\nDer wichtigste zuerst: Das Sättigungssignal braucht rund 20 Minuten, bis es ankommt. Wer eine Mahlzeit in zehn Minuten isst, isst zehn Minuten lang an einem Körper vorbei, der schon satt ist. Das hat nichts mit Disziplin zu tun — das ist reine Verzögerung.\n\nDer dritte Punkt ist der, bei dem fast alle falsch liegen: Nicht die halbe Portion nehmen, sondern den kleineren Teller. Dieselbe Menge sieht darauf nach mehr aus, und dein Auge isst mit, ob du willst oder nicht. Eine halbe Portion auf großem Teller fühlt sich nach Verzicht an. Dieselbe Menge auf kleinem Teller fühlt sich nach Essen an.\n\nSattwerden ist kein Willensakt. Es ist eine Frage von Zeit, Reihenfolge und Tellergröße.\n\nWas davon machst du schon? 👇',
 bild='Kleiner Teller neben großem Teller auf dunkler Arbeitsplatte, gleiche Portion',
 ziel='Kommentar'),

dict(
 n=17,
 tag='Mi',
 w=3,
 fmt='R',
 art='Reel · 20 Sek.',
 titel='Das Glas neben dem Bett',
 hook='Stell dir abends ein Glas Wasser ans Bett. Nicht wegen der Nacht.',
 slides=[
  '0–4 Sek: Makro, Glas Wasser auf Nachttisch, Morgenlicht.',
  '4–10 Sek: Nach sieben Stunden ohne Flüssigkeit ist der Körper morgens am trockensten.',
  '10–15 Sek: Was sich dann wie Hunger anfühlt, ist oft Durst.',
  '15–18 Sek: Das Glas steht schon da. Du musst nichts entscheiden.',
  '18–20 Sek: Endcard.',
 ],
 caption='Das Glas neben dem Bett wirkt nicht nachts, sondern morgens.\n\nNach sieben Stunden ohne Flüssigkeit ist der Körper am trockensten. Und was sich morgens wie Heißhunger anfühlt, ist oft schlicht Durst.\n\nDer eigentliche Trick ist aber nicht das Wasser. Es ist, dass du die Entscheidung am Abend triffst — wenn du sie leicht triffst — und morgens nur noch ausführst.\n\nSo funktionieren fast alle Gewohnheiten, die halten.',
 bild='Reel-B-Roll: Makro Wasserglas auf Nachttisch, Morgensonne, Hand greift danach',
 ziel='Speichern'),

dict(
 n=18,
 tag='Do',
 w=3,
 fmt='C',
 art='Einzelbild',
 titel='Das Rezept',
 hook='Rezeptblock, handschriftlich ausgefüllt: „30 Minuten gehen. Täglich. Kein Ersatzpräparat verfügbar.“',
 slides=[
  'Ein Bild: Rezeptblock auf einem Praxistisch, handschriftlich ausgefüllt. Text ist Teil des Objekts.',
 ],
 caption='Es gibt keine Tablette, die das ersetzt.\n\nRegelmäßiges Gehen wirkt auf Blutdruck, Blutzucker, Schlaf, Stimmung und Gelenke gleichzeitig. Kein einzelnes Präparat deckt diese Kombination ab — und keins hat so wenige Nebenwirkungen.\n\nDas heißt nicht, dass Medikamente überflüssig sind. Es heißt, dass hier etwas kostenlos verfügbar ist, das sonst niemand verkaufen könnte.\n\n30 Minuten. Nicht am Stück, wenn es nicht anders geht.\n\nWie viele Minuten waren es heute bei dir? 👇',
 bild='a prescription pad on a desk with a pen, clinical side light, shallow depth of field',
 ziel='Kommentar (Minuten)'),

dict(
 n=19,
 tag='Fr',
 w=3,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Der Bauch, der nicht weggeht',
 hook='Er trainierte 14 Monate den Bauch. Weggegangen ist er, als er aufhörte.',
 slides=[
  'Cover — der Hook.',
  'Er hat durchgehalten. 14 Monate, jeden Abend, ohne eine Woche Pause.',
  'Die Bauchmuskeln waren am Ende deutlich kräftiger. Messbar, sichtbar, fester.',
  'Es lag nicht an der Ausführung: 15 Minuten täglich, saubere Technik, Ernährung unverändert.',
  'Es lag auch nicht am Gewicht. Das war in 14 Monaten fast gleich geblieben.',
  'Es lag daran, dass er die falsche Schicht trainierte.',
  'Der Muskel liegt unter dem Fett. Der Reiz erreicht die Schicht darüber nicht.',
  'Fett verschwindet nicht dort, wo der Muskel arbeitet — der Körper zieht Energie aus dem ganzen Depot.',
  'Was den Umfang beeinflusst: Gesamtbilanz, Schlaf, Alkohol, Stresslast.',
  'Er tauschte 15 Minuten Bauch gegen 40 Minuten Gehen und aß rund 200 kcal weniger.',
  'Payoff: Das Bauchtraining war nicht falsch. Es war die Antwort auf eine andere Frage.',
  'CTA-Slide.',
 ],
 caption='Er trainierte 14 Monate den Bauch. Weggegangen ist er, als er aufhörte.\n\nEr hat durchgehalten — jeden Abend, ohne eine Woche Pause. Die Bauchmuskeln waren am Ende deutlich kräftiger. Der Umfang war derselbe.\n\nEs lag nicht an der Ausführung. Es lag daran, dass er die falsche Schicht trainierte: Der Muskel liegt unter dem Fett, und der Reiz erreicht die Schicht darüber nicht.\n\nFett verschwindet nicht dort, wo der Muskel arbeitet. Der Körper zieht Energie aus dem gesamten Depot, nicht aus der trainierten Region. Was den Umfang beeinflusst, sind Gesamtbilanz, Schlaf, Alkohol und Stresslast.\n\nEr tauschte 15 Minuten Bauchübungen gegen 40 Minuten Gehen und aß etwa 200 Kalorien weniger. Nach fünf Monaten waren es sechs Zentimeter.\n\nDas Bauchtraining war nicht falsch. Es war die Antwort auf eine andere Frage.\n\nWas hast du schon monatelang gemacht, ohne dass sich was tat? 👇',
 bild='a rolled yoga mat leaning in a corner of a living room, evening light, dust visible in the air',
 ziel='Kommentar'),

dict(
 n=20,
 tag='Sa',
 w=3,
 fmt='R',
 art='Reel · 24 Sek.',
 titel='Der Einkaufswagen',
 hook='Zwei Einkaufswagen. Gleicher Preis. Fünf Tage Unterschied.',
 slides=[
  '0–4 Sek: Hände-POV, zwei Wagen von oben.',
  '4–11 Sek: Links: Fertigpizza, Chips, Softdrinks, Fruchtjoghurt.',
  '11–18 Sek: Rechts: Haferflocken, Eier, Skyr, Hähnchen, Gemüse, Reis.',
  '18–21 Sek: Beides rund 40 Euro. Rechts kommst du fünf Tage weit.',
  '21–24 Sek: Endcard.',
 ],
 caption='Zwei Einkaufswagen, ungefähr derselbe Preis.\n\nLinks: Fertigpizza, Chips, Softdrinks, Fruchtjoghurt. Rechts: Haferflocken, Eier, Skyr, Hähnchen, Gemüse, Reis.\n\nMit dem rechten Wagen kochst du fünf Tage. Mit dem linken hast du drei Abende überbrückt.\n\n„Gesund essen ist teuer“ stimmt für Superfood-Pulver und Bio-Fertiggerichte. Für Haferflocken, Eier und Tiefkühlgemüse stimmt es nicht.\n\nSpeicher dir das für Samstag.',
 bild='Reel-B-Roll: zwei Einkaufswagen von oben, gleicher Supermarktboden, gleiches Licht',
 ziel='Speichern'),

dict(
 n=21,
 tag='So',
 w=3,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Sätze über Schlaf',
 hook='Sieben Sätze über Schlaf. Der wichtigste hat nichts mit dem Abend zu tun.',
 slides=[
  'Cover: Sieben Sätze über Schlaf — Der wichtigste hat nichts mit dem Abend zu tun.',
  'Steh immer gleich auf / nicht geh immer gleich ins Bett — Beleg: Die Aufstehzeit stellt die innere Uhr. Die Zubettgehzeit folgt ihr, nicht umgekehrt.',
  'Geh morgens ins Licht / nicht abends ans Handy — Beleg: Zehn Minuten Tageslicht am Morgen stellen den Rhythmus schärfer als jede Abendroutine.',
  'Kühl das Zimmer / nicht dich — Beleg: Der Körper senkt zum Einschlafen seine Kerntemperatur. Ein warmes Zimmer arbeitet dagegen.',
  'Trink den Wein früher / nicht weniger — Beleg: Alkohol lässt dich schneller einschlafen und zerlegt die zweite Nachthälfte. Der Zeitpunkt ändert mehr als die Menge.',
  'Zieh den Kaffee vor / nicht streich ihn — Beleg: Koffein hat rund 5 bis 6 Stunden Halbwertszeit. Der Espresso um 16 Uhr wirkt um 22 Uhr noch.',
  'Schreib es auf / nicht denk es zu Ende — Beleg: Ein Zettel neben dem Bett beendet Gedankenkreisen schneller als der Versuch, es zu lösen.',
  'Zähl gute Nächte pro Woche / nicht Stunden pro Nacht — Beleg: Eine schlechte Nacht ist Statistik. Vier schlechte Nächte sind ein Muster.',
  'Erkenntnis: Schlaf beginnt nicht abends. Er beginnt morgens, wenn du aufstehst und ins Licht gehst.',
  'CTA-Slide.',
 ],
 caption='Sieben Sätze über Schlaf.\n\nDer wichtigste hat nichts mit dem Abend zu tun. Die meisten arbeiten an der Einschlafroutine — dunkles Zimmer, kein Bildschirm, Tee. Und stehen jeden Tag zu einer anderen Zeit auf.\n\nDabei stellt die Aufstehzeit die innere Uhr, nicht die Zubettgehzeit. Wer jeden Tag gleich aufsteht und morgens zehn Minuten ins Tageslicht geht, wird abends von allein müde. Wer am Wochenende drei Stunden länger liegen bleibt, hat sich einen kleinen Jetlag gebaut.\n\nDer zweite Punkt, der überrascht: Bei Alkohol ändert der Zeitpunkt mehr als die Menge. Alkohol lässt dich schneller einschlafen und zerlegt dafür die zweite Nachthälfte. Zwei Gläser um 18 Uhr sind etwas anderes als zwei Gläser um 22 Uhr.\n\nSchlaf beginnt nicht abends. Er beginnt morgens.\n\nWann stehst du am Wochenende auf? 👇',
 bild='Fenster mit Morgenlicht, Vorhang halb offen, ungemachtes Bett unscharf im Hintergrund',
 ziel='Kommentar'),

dict(
 n=22,
 tag='Mo',
 w=4,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Laufen ruiniert die Knie',
 hook='Sein Arzt riet ihm mit 51 vom Laufen ab. Zehn Jahre später hatte der Nachbar die besseren Knie.',
 slides=[
  'Cover — der Hook.',
  'Der Rat war gut gemeint. Und er stammte nicht aus einer Untersuchung.',
  'Er hielt sich zehn Jahre daran. Sein Nachbar lief weiter.',
  'Es lag nicht an den Genen: gleiches Alter, gleiches Gewicht, gleiche Wohngegend.',
  'Zehn Jahre später hatte der Nachbar die gesünderen Knie. Nicht die schlechteren.',
  'Der Grund liegt darin, wie Knorpel überhaupt versorgt wird.',
  'Knorpel hat keine eigene Blutversorgung. Er lebt von Belastung und Entlastung.',
  'Bewegung ist für ihn Versorgung, nicht Verschleiß.',
  'In Untersuchungen ist Freizeitlaufen nicht mit mehr Kniearthrose verbunden. Auffällig sind zwei andere Gruppen: sehr hohe Umfänge — und Menschen, die sich gar nicht bewegen.',
  'Was Knie tatsächlich überlastet: zu schnelle Steigerung und zu wenig Muskulatur drumherum.',
  'Payoff: Er fing mit 61 an. Der Satz, der ihn zehn Jahre gekostet hat, war nie überprüft worden.',
  'CTA-Slide.',
 ],
 caption='Sein Arzt riet ihm mit 51 vom Laufen ab.\n\nDer Rat war gut gemeint — und er stammte nicht aus einer Untersuchung. Er hielt sich zehn Jahre daran. Sein Nachbar, gleiches Alter, gleiches Gewicht, lief weiter. Zehn Jahre später hatte der Nachbar die gesünderen Knie.\n\nDer Grund liegt darin, wie Knorpel versorgt wird: Er hat keine eigene Blutversorgung und lebt von Belastung und Entlastung. Bewegung ist für ihn Versorgung, nicht Verschleiß.\n\nIn Untersuchungen ist regelmäßiges Freizeitlaufen nicht mit mehr Kniearthrose verbunden. Auffällig sind zwei andere Gruppen: Menschen mit sehr hohem Trainingsumfang — und Menschen, die sich gar nicht bewegen.\n\nWas Knie tatsächlich überlastet, sind zu schnelle Steigerung und zu wenig Muskulatur drumherum.\n\nEr fing mit 61 an: erst Gehen, dann im Wechsel, dazu zweimal die Woche Beintraining. Heute läuft er fünf Kilometer, beschwerdefrei.\n\nDer Satz, der ihn zehn Jahre gekostet hat, war nie überprüft worden.\n\nBei bestehenden Knieproblemen gehört die Frage trotzdem in ärztliche Hände — dieser Beitrag ersetzt das nicht.',
 bild='empty running track at dawn, wet surface, no people, cool blue light',
 ziel='Kommentar'),

dict(
 n=23,
 tag='Di',
 w=4,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Sätze über Anfangen',
 hook='Sieben Sätze über Anfangen. Der sechste klingt nach Aufgeben und ist das Gegenteil.',
 slides=[
  'Cover: Sieben Sätze über Anfangen — Der sechste klingt nach Aufgeben. Er ist das Gegenteil.',
  'Setz einen Termin / nicht ein Ziel — Beleg: Ein Ziel hat kein Datum im Kalender. Ein Termin schon.',
  'Änder eine Sache / nicht dein Leben — Beleg: Wer alles gleichzeitig ändert, ändert nach drei Wochen nichts mehr.',
  'Fang zu klein an / nicht zu spät — Beleg: Zehn Minuten, die du machst, schlagen 60, die du planst.',
  'Mach es schlecht / nicht gar nicht — Beleg: Die halbe Einheit hält die Gewohnheit am Leben. Die ausgelassene reißt sie ab.',
  'Häng es an etwas dran / nicht such einen freien Slot — Beleg: Nach dem Kaffee, nach dem Zähneputzen. Eine bestehende Gewohnheit trägt die neue.',
  'Rechne mit dem Rückfall / nicht mit der Strähne — Beleg: Wer den schlechten Tag einplant, hört an ihm nicht auf. Wer ihn nicht einplant, nimmt ihn als Beweis.',
  'Fang Dienstag an / nicht Montag — Beleg: Der Montag trägt die Erwartung, dass jetzt alles anders wird. Der Dienstag trägt nur den Termin.',
  'Erkenntnis: Anfangen scheitert selten am ersten Tag. Es scheitert am ersten Tag, an dem es nicht klappt.',
  'CTA-Slide.',
 ],
 caption='Sieben Sätze über Anfangen.\n\nDer sechste klingt nach Aufgeben und ist das Gegenteil: Rechne mit dem Rückfall.\n\nFast jeder plant den perfekten Verlauf — und hat für den schlechten Tag keinen Plan. Dann kommt er, und weil er nicht vorgesehen war, wird er zum Beweis: „Ich schaffe das eh nicht." Wer den schlechten Tag von vornherein einplant, hat an ihm keine Beweislage, sondern einen Dienstag.\n\nUnd der letzte Punkt ist ernst gemeint. Der Montag trägt die Erwartung, dass ab jetzt alles anders wird. Wenn der Montag schiefgeht, ist die ganze Woche verbrannt. Der Dienstag trägt keine Erwartung — nur einen Termin.\n\nAnfangen scheitert selten am ersten Tag. Es scheitert am ersten Tag, an dem es nicht klappt.\n\nWoran ist es bei dir zuletzt gescheitert? 👇',
 bild='Küchenkalender an der Wand, ein Tag mit Stift markiert, ruhiges Morgenlicht',
 ziel='Kommentar'),

dict(
 n=24,
 tag='Mi',
 w=4,
 fmt='R',
 art='Reel · 20 Sek.',
 titel='Die Treppe',
 hook='Nimm die Treppe. Nicht wegen der Kalorien.',
 slides=[
  '0–4 Sek: Detail-Makro Treppenhaus, Füße von hinten.',
  '4–10 Sek: Zwei Stockwerke verbrennen kaum Kalorien. Darum geht es nicht.',
  '10–16 Sek: Treppensteigen belastet Beine und Kreislauf kurz und intensiv — genau der Reiz, der im Alltag fehlt.',
  '16–18 Sek: Zwölfmal am Tag ergibt das mehr als eine Trainingseinheit die Woche.',
  '18–20 Sek: Endcard.',
 ],
 caption='Treppe statt Aufzug — aber nicht wegen der Kalorien.\n\nZwei Stockwerke verbrennen fast nichts. Interessant ist etwas anderes: Treppensteigen belastet Beinmuskulatur und Kreislauf kurz und intensiv. Genau dieser Reiz fehlt in einem Alltag, der sonst nur aus Gehen und Sitzen besteht.\n\nZwölfmal am Tag, fünf Tage die Woche, ergibt in Summe mehr als eine Trainingseinheit — die du nie einplanen musstest.\n\nSpeicher dir das für morgen früh im Büro.',
 bild='Reel-B-Roll: Treppenhaus von unten, Füße auf Stufen, Handlauf-Detail',
 ziel='Speichern'),

dict(
 n=25,
 tag='Do',
 w=4,
 fmt='C',
 art='Einzelbild',
 titel='Die Packungsrückseite',
 hook='Nährwerttabelle: Zucker 12 g. Direkt daneben, klein: Portion 25 g. Packungsinhalt 500 g.',
 slides=[
  'Ein Bild: Makro auf die Rückseite einer Müslipackung. Nährwerttabelle scharf lesbar, Zuckerangabe pro Portion, darunter die Portionsgröße in kleinerer Schrift. Text ist echter Packungsaufdruck, kein Overlay.',
 ],
 caption='12 Gramm Zucker. Klingt vertretbar.\n\nBis du zwei Zeilen tiefer schaust: pro Portion. Und die Portion ist mit 25 Gramm angegeben.\n\n25 Gramm Müsli sind zwei Esslöffel. Niemand isst zwei Esslöffel Müsli. Eine normale Schüssel sind eher 80 bis 100 Gramm — und damit landest du bei rund 40 bis 48 Gramm Zucker, bevor die Milch dazukommt.\n\nDas ist nicht illegal und auch nicht versteckt. Es steht da. Es steht nur klein da, und es steht neben der Zahl, die groß aussieht.\n\nDeshalb ist die wichtigste Angabe auf jeder Packung nicht der Zuckergehalt. Es ist die Portionsgröße daneben.\n\nSchau heute Abend mal auf eine Packung bei dir. Was steht da? 👇',
 bild='Makro auf eine Packungsrückseite, Nährwerttabelle im Fokus, kühles Licht von der Seite',
 ziel='Kommentar (Minuten)'),

dict(
 n=26,
 tag='Fr',
 w=4,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='30 Gramm',
 hook='Sie aß jeden Tag Salat und hatte trotzdem ständig Verdauungsprobleme. Es fehlten 18 Gramm.',
 slides=[
  'Cover — der Hook.',
  'Sie aß mehr Gemüse als die meisten. Salat zum Mittag, Obst am Nachmittag, jeden Tag.',
  'Die Beschwerden kamen trotzdem — und wurden schlimmer, je gesünder sie aß.',
  'Es lag nicht an einer Unverträglichkeit. Zwei Tests, beide unauffällig.',
  'Es lag auch nicht an zu wenig Gemüse. Sie lag über dem Durchschnitt.',
  'Es lag daran, dass ihr Salat weniger liefert, als er aussieht.',
  'Empfohlen werden rund 30 Gramm Ballaststoffe am Tag. Sie kam auf etwa 12.',
  'Salat besteht überwiegend aus Wasser. Drei Schüsseln Eisbergsalat liefern weniger als eine Portion Linsen.',
  'Die großen Quellen sind die unauffälligen: Hülsenfrüchte, Vollkorn, Haferflocken, Nüsse.',
  'Wichtig: langsam steigern und mehr trinken. Wer von 12 auf 30 springt, hat erst mal mehr Beschwerden.',
  'Payoff: Sie hat nichts weggelassen, sie hat dazugelegt. Es fehlten keine Regeln — es fehlten 18 Gramm.',
  'CTA-Slide.',
 ],
 caption='Sie aß jeden Tag Salat und hatte trotzdem ständig Verdauungsprobleme.\n\nSie aß mehr Gemüse als die meisten — Salat zum Mittag, Obst am Nachmittag. Die Beschwerden kamen trotzdem, und sie wurden schlimmer, je gesünder sie aß. Zwei Unverträglichkeitstests: beide unauffällig.\n\nEs lag daran, dass Salat weniger liefert, als er aussieht. Empfohlen werden rund 30 Gramm Ballaststoffe am Tag, sie kam auf etwa 12. Salat besteht überwiegend aus Wasser — drei Schüsseln Eisbergsalat liefern weniger als eine Portion Linsen.\n\nDie großen Quellen sind die unauffälligen: Hülsenfrüchte, Vollkorn, Haferflocken, Nüsse.\n\nWichtig, sonst geht es nach hinten los: langsam steigern und mehr trinken. Wer von 12 auf 30 Gramm springt, hat erst mal mehr Beschwerden, nicht weniger.\n\nSie hat nichts weggelassen. Sie hat dazugelegt. Nach sechs Wochen war Ruhe.\n\nEs fehlten keine Regeln. Es fehlten 18 Gramm.\n\nDieser Beitrag informiert und ersetzt keine ärztliche Abklärung.',
 bild='dried lentils and oats in two open glass jars on a dark counter, single soft light',
 ziel='Speichern'),

dict(
 n=27,
 tag='Sa',
 w=4,
 fmt='R',
 art='Reel · 22 Sek.',
 titel='Die Hantel und die Einkaufstüte',
 hook='Warum Krafttraining nichts mit dem Studio zu tun hat.',
 slides=[
  '0–4 Sek: Split: links Hantel, rechts volle Einkaufstüte.',
  '4–11 Sek: Beides ist Last, die dein Körper stabilisieren muss.',
  '11–17 Sek: Wer Kraft trainiert, trainiert nicht fürs Studio, sondern für Tüten, Treppen und das Aufstehen mit 70.',
  '17–20 Sek: Deshalb ist es das Training, das am spätesten unwichtig wird.',
  '20–22 Sek: Endcard.',
 ],
 caption='Krafttraining hat wenig mit dem Studio zu tun.\n\nEine Hantel und eine volle Einkaufstüte sind für den Körper dieselbe Aufgabe: eine Last, die stabilisiert und bewegt werden muss.\n\nDeshalb trainiert man Kraft nicht für Fotos, sondern für Tüten, Treppen, Kinder auf dem Arm und das Aufstehen vom Stuhl mit 70.\n\nEs ist das Training, das am spätesten unwichtig wird — und das, mit dem die meisten am spätesten anfangen.\n\nSpeicher es dir für den Tag, an dem du keine Lust hast.',
 bild='Reel-B-Roll: Split-Screen Hantel auf Boden / gefüllte Einkaufstüte in Hand, gleiches Licht',
 ziel='Speichern'),

dict(
 n=28,
 tag='So',
 w=4,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='Sieben Sätze über den Tag, an dem es nicht klappt',
 hook='Sieben Sätze für den Tag, an dem es nicht klappt. Der vierte rettet die meisten Wochen.',
 slides=[
  'Cover: Sieben Sätze für den Tag,<br>an dem es nicht klappt — Der vierte rettet mehr Wochen als jeder Motivationsspruch.',
  'Bewerte den Monat / nicht die Mahlzeit — Beleg: Eine Mahlzeit ist rund ein Prozent deines Monats. Sie kann ihn nicht entscheiden.',
  'Zähl die Wochen / nicht die Tage — Beleg: In Tagen gemessen ist jede Woche ein Auf und Ab. In Wochen gemessen siehst du die Richtung.',
  'Zwei schlechte Tage sind zwei Tage / nicht ein Rückfall — Beleg: Was du sie nennst, entscheidet, ob am dritten Tag noch etwas läuft.',
  'Nimm die halbe Einheit / nicht keine — Beleg: Zwanzig Minuten halten die Gewohnheit. Null unterbricht sie — und das Wiederanfangen kostet mehr.',
  'Mach den nächsten Schritt / nicht den ganzen Plan neu — Beleg: Der neue Plan fühlt sich nach Fortschritt an und ist meist nur eine Pause mit Papier.',
  'Frag, was schiefging / nicht warum du so bist — Beleg: Der Grund liegt fast immer im Ablauf: kein Essen dabei, kein Termin, kein Schlaf.',
  'Bleib mittelmäßig dabei / nicht hör perfekt auf — Beleg: Zwölf mittelmäßige Monate schlagen sechs perfekte Wochen. Das ist die ganze Rechnung.',
  'Erkenntnis: Der Unterschied zwischen den Leuten, die es schaffen, ist nicht die gute Woche. Es ist, was am Tag nach der schlechten passiert.',
  'CTA-Slide.',
 ],
 caption='Sieben Sätze für den Tag, an dem es nicht klappt.\n\nDer vierte rettet mehr Wochen als jeder Motivationsspruch: Nimm die halbe Einheit statt keiner.\n\nZwanzig Minuten sind trainingsmäßig fast nichts — aber sie halten die Gewohnheit am Leben. Null unterbricht sie, und das Wiederanfangen kostet mehr Kraft als die ausgefallene Einheit gespart hat. Deshalb ist die schlechte Einheit fast immer die richtige Entscheidung.\n\nUnd der dritte Punkt entscheidet oft alles: Zwei schlechte Tage sind zwei Tage. Sobald du sie „Rückfall" nennst, hast du eine Geschichte, in der es sich lohnt, auch den dritten aufzugeben.\n\nDer Unterschied zwischen den Leuten, die es schaffen, ist nicht die gute Woche. Es ist, was am Tag nach der schlechten passiert.\n\nWie sah dein letzter schlechter Tag aus? 👇',
 bild='Regennasse Fensterscheibe von innen, dahinter unscharf eine Straße am Abend',
 ziel='Kommentar'),

dict(
 n=29,
 tag='Mo',
 w=5,
 fmt='A',
 art='Karussell · 12 Slides',
 titel='Der Schrittzähler',
 hook='Er ging 12.000 Schritte am Tag und nahm nicht ab. Ein Wert erklärte alles.',
 slides=[
  'Cover — der Hook.',
  'Die Uhr zeigte jeden Abend eine Zahl, auf die die meisten stolz wären.',
  '44, Einzelhandel, den ganzen Tag auf den Beinen. Seit zwei Jahren dasselbe Gewicht.',
  'Es lag nicht an der Bewegung. Er ging mehr als fast alle in seinem Umfeld.',
  'Es lag auch nicht an der Schilddrüse. Zweimal geprüft, beide Male unauffällig.',
  'Es lag an den drei Stunden, die auf der Uhr nicht auftauchen.',
  'Schritte sind Alltagsbewegung, kein Training — 12.000 über neun Stunden wirken anders als 12.000 am Stück.',
  'Dazu ein Effekt, den kaum jemand einrechnet: Wer sich viel bewegt, isst oft unbewusst mehr.',
  'Sein Abendessen war um 21 Uhr. Danach Snacks bis Mitternacht.',
  'Er ließ die Schritte, wie sie waren. Er zog nur das Abendessen auf 18:30 vor.',
  'Payoff: Nach vier Monaten fünf Kilo. Er musste sich nicht mehr bewegen — er musste früher aufhören.',
  'CTA-Slide.',
 ],
 caption='Er ging 12.000 Schritte am Tag und nahm nicht ab.\n\n44 Jahre, Einzelhandel, den ganzen Tag auf den Beinen. Die Uhr zeigte jeden Abend eine Zahl, auf die die meisten stolz wären. Und trotzdem seit zwei Jahren dasselbe Gewicht.\n\nEs lag nicht an der Bewegung. Es lag an den drei Stunden, die auf der Uhr nicht auftauchen.\n\nSchritte sind Alltagsbewegung, kein Training: 12.000 über neun Stunden im Laden wirken anders als 12.000 am Stück. Dazu kommt ein Effekt, den kaum jemand einrechnet — wer sich viel bewegt, isst oft unbewusst mehr.\n\nSein Abendessen war um 21 Uhr, danach Snacks bis Mitternacht. Er ließ die Schritte, wie sie waren, und zog nur das Abendessen auf 18:30 vor. Nach vier Monaten waren fünf Kilo weg.\n\nEr musste sich nicht mehr bewegen. Er musste früher aufhören.\n\nWann isst du zu Abend? 👇',
 bild='a smartwatch face on a nightstand showing a step count, dark room, single cool light',
 ziel='Kommentar (Uhrzeit)'),

dict(
 n=30,
 tag='Di',
 w=5,
 fmt='B',
 art='Karussell · 10 Slides',
 titel='30 Tage in sieben Sätzen',
 hook='30 Tage Gesundheitsakte in sieben Sätzen. Der letzte fasst alle zusammen.',
 slides=[
  'Cover: 30 Tage in sieben Sätzen — Jeder Satz gehört zu einem Fall aus diesem Monat.',
  'Ändere den Zeitpunkt / nicht die Menge — Beleg: Akte 001: Derselbe Kaffee, drei Stunden früher — und die erste Nachthälfte kam zurück.',
  'Steh alle 30 Minuten auf / nicht abends ins Studio — Beleg: Akte 005: Neun Stunden Sitzen holt eine Trainingsstunde nicht auf.',
  'Leg Eiweiß dazu / nicht Kalorien weg — Beleg: Akte 026: Nicht weniger essen, sondern anders. Eiweiß sättigt pro Kalorie am stärksten.',
  'Miss den Monat / nicht den Morgen — Beleg: Akte 011: Tageswerte schwanken um bis zu zwei Kilo. Wochenwerte zeigen die Richtung.',
  'Belaste die Knie / nicht schone sie — Beleg: Akte 022: Knorpel hat keine Blutversorgung. Er lebt von Belastung, nicht von Schonung.',
  'Geh nach dem Essen / nicht nach dem Kaffee ins Sofa — Beleg: Akte 003: Arbeitende Muskeln ziehen Glukose auch ohne Insulin aus dem Blut.',
  'Bleib zwölf Monate dabei / nicht sechs Wochen perfekt — Beleg: Akte 007: Die einzige Regel, die alle anderen überhaupt erst wirksam macht.',
  'Erkenntnis: Kein einziger Fall in diesem Monat wurde durch mehr Disziplin gelöst. Alle durch einen anderen Zeitpunkt.',
  'CTA-Slide.',
 ],
 caption='30 Tage Gesundheitsakte in sieben Sätzen.\n\nWenn du eine Sache aus diesem Monat mitnimmst, dann die: Kein einziger Fall wurde durch mehr Disziplin gelöst.\n\nDer Espresso musste nicht weg — er musste drei Stunden früher. Der Rücken brauchte keine neue Übung — er brauchte alle 30 Minuten zwei Minuten Stehen. Der Salat war nicht falsch — es fehlten 18 Gramm Ballaststoffe. Jedes Mal war die Antwort ein anderer Zeitpunkt oder ein zusätzlicher Baustein, nie mehr Willenskraft.\n\nDas ist auch der Grund, warum die meisten Pläne scheitern. Sie verlangen mehr von einer Ressource, die schon knapp ist.\n\nDanke, dass du 30 Tage dabei warst. Es geht weiter.\n\nWelcher Fall ist dir geblieben? 👇',
 bild='Stapel geschlossener Aktenmappen auf dunklem Tisch, eine Schreibtischlampe seitlich',
 ziel='Kommentar'),

]
